const bookData = {
  title: "The Last Sins",
  tagline: "Beneath every virtue lies a single sin.",
  chapters: [
    {
      id: 1,
      title: "The City Beneath the Clock",
      content: [
        "The bells rang seven times.",
        "Their deep, solemn echoes drifted across London, rolling over rooftops and slipping through the thick morning fog that swallowed the city whole.",
        "To strangers, London was magnificent.",
        "Grand buildings stood proudly beneath the gray sky. Carriages rattled across cobblestone streets. Merchants prepared their stalls while smoke curled from countless chimneys.",
        "From a distance, it looked like the greatest city in the world.",
        "But distance was a liar.",
        "Beneath the beauty hid corruption. Beneath the wealth hid greed. Beneath every smiling face hid a secret waiting for the right moment to emerge.",
        "London was a city that wore masks.",
        "And no one understood that better than the people who lived at its bottom.",
        "Far from the noble districts and luxurious estates stood a forgotten corner of the city—a place ignored by politicians and abandoned by opportunity.",
        "The orphan quarter.",
        "Its buildings were old. Its streets were narrow. Rainwater collected in broken stone pathways, and poverty clung to every wall like a permanent stain.",
        "Among those streets walked a young man with a worn brown coat and a pocket watch hanging from his vest.",
        "His name was Ronan.",
        "And at that particular moment, he was chasing a cat.",
        "\"Stop! Come back here!\"",
        "The orange cat darted through an alleyway.",
        "A basket of apples overturned as it passed.",
        "A merchant immediately shouted in protest.",
        "\"My apples!\"",
        "\"Sorry!\" Ronan called back. \"I'll pay for them later!\"",
        "The cat leaped over a wooden fence.",
        "Ronan followed.",
        "After several exhausting minutes, he finally cornered the animal beside a stack of crates.",
        "The cat hissed.",
        "Ronan sighed.",
        "\"You're causing more trouble than half the people in this city.\"",
        "He carefully picked it up.",
        "Moments later, a small girl came running down the street.",
        "\"Mr Ronan!\"",
        "The relief on her face was immediate.",
        "Ronan handed over the cat.",
        "The little girl hugged it tightly.",
        "\"Thank you!\"",
        "\"You should watch him more carefully.\"",
        "\"I will.\"",
        "\"You said that last time.\"",
        "The girl laughed.",
        "\"So you'll help me again if he runs away?\"",
        "Ronan smiled.",
        "\"Probably.\"",
        "The girl grinned before running home.",
        "Ronan watched her disappear into the crowd.",
        "A small smile remained on his face.",
        "That was the kind of work he usually received.",
        "Lost pets.",
        "Missing belongings.",
        "Neighborhood disputes.",
        "Nothing exciting.",
        "Nothing dangerous.",
        "Certainly nothing worthy of the title detective.",
        "The government didn't consider him one.",
        "Most officials barely knew he existed.",
        "But Ronan didn't mind.",
        "Helping people was enough.",
        "At least, it used to be.",
        "The city grew busier as the day passed.",
        "Workers hurried through the streets.",
        "Merchants argued with customers.",
        "Children laughed while chasing each other between market stalls.",
        "For a brief moment, everything felt normal.",
        "Then a carriage appeared.",
        "Unlike the others, this one immediately commanded attention.",
        "Its black exterior gleamed despite the cloudy sky.",
        "A silver crest decorated its side.",
        "The reaction was instant.",
        "People stepped aside.",
        "Conversations stopped.",
        "Heads lowered.",
        "Ronan watched silently as the carriage rolled past.",
        "Even from a distance, he recognized the emblem.",
        "Ashford.",
        "One of the most influential noble families in London.",
        "Their wealth stretched across the kingdom.",
        "Their influence reached places ordinary citizens could never imagine.",
        "People respected them.",
        "People feared them.",
        "And people never questioned them.",
        "The carriage disappeared into the fog.",
        "Life resumed.",
        "Ronan reached into his coat and removed the old pocket watch he carried everywhere.",
        "The silver casing was scratched.",
        "Its chain had lost its shine years ago.",
        "Yet the watch continued to tick faithfully.",
        "Tick.",
        "Tick.",
        "Tick.",
        "For reasons he couldn't explain, the sound always comforted him.",
        "As if it reminded him that no matter how difficult life became, time continued moving forward.",
        "The sky darkened.",
        "Rain began to fall.",
        "Street lamps flickered awake one by one.",
        "The city prepared for another ordinary evening.",
        "Then the screaming started.",
        "At first, nobody understood what was happening.",
        "A woman rushed through the street.",
        "Several guards followed behind her.",
        "Their faces were pale.",
        "Their movements frantic.",
        "People immediately gathered.",
        "\"What happened?\"",
        "\"Is there a fire?\"",
        "\"No.\"",
        "The woman looked as though she had seen a ghost.",
        "Her voice trembled.",
        "\"A body.\"",
        "The crowd fell silent.",
        "\"A body was found near London Bridge.\"",
        "A chill ran through Ronan.",
        "Something about the woman's expression felt wrong.",
        "This wasn't ordinary fear.",
        "It was horror.",
        "Within minutes, rumors spread across the city.",
        "People abandoned their work.",
        "Shopkeepers left their stores.",
        "Citizens flooded toward London Bridge.",
        "Ronan followed.",
        "The rain intensified.",
        "The closer he got, the heavier the atmosphere became.",
        "More guards appeared.",
        "More barriers.",
        "More frightened faces.",
        "By the time he reached the bridge, dozens of officers had already secured the area.",
        "Nobody was speaking.",
        "Nobody dared.",
        "Ronan slowly moved through the crowd.",
        "Then he saw it.",
        "The body.",
        "For a moment, he couldn't breathe.",
        "The victim lay motionless on the wet stone.",
        "The brutality was unlike anything he had ever witnessed.",
        "Even experienced guards looked disturbed.",
        "One officer turned away and vomited.",
        "Another stared in stunned silence.",
        "Ronan felt his stomach tighten.",
        "Whoever had done this hadn't simply wanted to kill.",
        "They had wanted to send a message.",
        "Then he noticed something beside the corpse.",
        "A single playing card.",
        "Rainwater flowed across its surface.",
        "Yet the image remained perfectly visible.",
        "A Fool.",
        "The card rested silently beside the dead man.",
        "As if it had been placed there intentionally.",
        "As if it were a signature.",
        "Thunder echoed above the city.",
        "Far away, the great clock tower rang once more.",
        "And standing among the crowd, staring at that strange card, Ronan felt a feeling he had never experienced before.",
        "A feeling that something terrible had just entered London.",
        "And that his life would never be the same again."
      ]
    },
    {
      id: 2,
      title: "The London Bridge Case",
      content: [
        "18 July",
        "By the time the first rays of sunlight touched the rooftops of London, the murder had become the only thing the city could talk about.",
        "The streets were louder than usual.",
        "Not because of business. Not because of celebration. But because of fear.",
        "Merchants discussed the incident while opening their shops. Workers argued about it before leaving for the factories. Coachmen exchanged rumors while waiting for passengers.",
        "Even children whispered about the mysterious body found on London Bridge the previous night.",
        "The newspapers had sold out before breakfast. Every headline carried the same story: A Powerful Minister Found Dead on London Bridge.",
        "Nobody knew the truth. Only rumors.",
        "\"I heard he was murdered before midnight.\"",
        "\"No... someone said it happened at dawn.\"",
        "\"They say the Royal Palace has already sealed the bridge.\"",
        "\"My cousin works near Westminster. He says the ministers haven't slept all night.\"",
        "\"And the killer... They say he left something beside the body. A playing card. The Fool.\"",
        "Every conversation ended with silence. For the first time in years... London felt uneasy.",
        "Far from Westminster... In one of London's poorest neighborhoods...",
        "A small wooden door slowly opened. Ronan stepped outside.",
        "His home was barely enough for one person. A worn-out table. A single chair. A bookshelf overflowing with old case files. Nothing luxurious. Nothing unnecessary.",
        "He quietly reached into his coat pocket. Three copper coins. He stared at them for a second before closing his hand. That was all he had. Breakfast... Or nothing.",
        "The smell of freshly baked bread drifted through the morning air. Without saying a word, Ronan began walking toward the neighborhood bakery.",
        "The bakery was already crowded. Fresh loaves filled the shelves. Golden crusts. Soft white bread. Warm rolls fresh from the oven.",
        "Ronan looked at them only briefly. Then his eyes moved toward a small basket beneath the counter. Yesterday's bread. Hard. Dry. Cheap.",
        "The old baker looked up and smiled. \"Morning, Ronan.\"",
        "\"Morning.\"",
        "Without asking any questions, the baker reached for the stale loaf. \"The usual?\"",
        "Ronan nodded. \"The usual.\"",
        "For a moment... The baker glanced toward the fresh bread. His expression softened. He wanted to help.",
        "But another customer entered. A wealthy noblewoman dressed in expensive clothes. The baker quietly placed the fresh loaf back where it belonged. He wrapped the stale bread instead. \"I'm sorry.\"",
        "Ronan smiled gently. \"You don't have to be.\"",
        "The baker placed the loaf on the counter. \"Three copper.\"",
        "Ronan emptied every coin he owned onto the wooden counter. The metallic sound echoed through the quiet shop. The baker accepted the payment.",
        "As Ronan turned to leave... The old man spoke. \"One day... You'll be buying the fresh ones.\"",
        "Ronan looked back with a faint smile. \"I hope so.\"",
        "He stepped back into the streets of London. The loaf of bread rested beneath his arm. It wasn't heavy. Yet somehow... It felt like he was carrying the weight of his entire life.",
        "He disappeared into the morning crowd... While behind him, London continued whispering about the murder that had changed everything.",
        "Ronan walked slowly through the narrow streets of East London. The stale loaf rested beneath his arm while the city around him continued discussing the murder.",
        "No one noticed him. That was something he had grown accustomed to long ago. To most people, he was not a detective. He was simply another poor man in a worn-out coat. Another commoner trying to survive the day.",
        "As he passed a small marketplace, two well-dressed noble boys stepped out of a carriage. One of them accidentally brushed against Ronan's shoulder.",
        "The boy immediately stepped back as though he had touched something filthy. \"Watch where you're going.\"",
        "His friend pulled out a white handkerchief and dusted off the sleeve of his expensive coat. \"Leave him. They're commoners. They don't know any better.\"",
        "The boys laughed quietly before walking away. Ronan did not answer. He did not even turn around.",
        "Insults had stopped hurting him years ago. Growing up as an orphan had taught him a cruel lesson very early in life—The world was not divided between good people and bad people. It was divided between those with power... and those without it.",
        "A few minutes later, he reached the end of the street. An old building stood there, its paint faded and its wooden sign barely hanging above the entrance. St. Gabriel's Orphanage.",
        "Ronan stopped walking. The sight pulled him backward through time. He could almost hear the voices of children arguing over scraps of food. He could almost feel the cold stone floor beneath his feet.",
        "Memories returned one after another. Carrying sacks of rice that were heavier than he was. Selling newspapers before sunrise. Polishing strangers' boots for a single copper coin. Unloading carts until his hands bled.",
        "Some days he earned enough to eat. Some days he did not. No one had protected him. No one had rescued him. He survived because he learned how to keep moving forward.",
        "Ronan smiled faintly at the memory. \"If I had chosen factory work,\" he murmured to himself, \"I would probably have more money today.\"",
        "He looked down at the detective badge hidden beneath his coat. \"But I wouldn't be able to help people.\"",
        "That thought alone was enough. He turned away from the orphanage and continued toward home.",
        "By the time he reached his small house, the morning sun had climbed higher into the sky. Ronan unlocked the door and stepped inside.",
        "The room was quiet. Too quiet. He placed the loaf on the table and removed his coat. For the first time that morning, he allowed himself to sit down.",
        "His eyes drifted toward the stack of investigation files beside the window. The London Bridge murder refused to leave his thoughts. The blood. The wounds. The terror frozen on the victim's face.",
        "Ronan closed his eyes for a moment. Then came a knock at the door.",
        "Knock. Knock. Knock.",
        "A familiar voice called from outside. \"Ronan? You'd better open the door before I break it down.\"",
        "A small smile appeared on his face despite himself. \"Evelyn.\"",
        "He crossed the room and opened the door. Standing outside was a young woman in a dark coat, a leather notebook tucked beneath one arm. Chestnut hair framed her face, and her eyes carried the same sharp curiosity they had carried since childhood.",
        "\"So,\" she said, folding her arms, \"you really forgot about me?\"",
        "Ronan chuckled softly. \"I was hoping you had forgotten where I live.\"",
        "Evelyn rolled her eyes. \"After twenty years? Impossible.\"",
        "Without waiting for permission, she stepped inside. Her gaze moved around the tiny room. The cracked walls. The old table. The overflowing bookshelf. The single chair. Nothing had changed.",
        "She sighed. \"Ronan... this place still looks exactly the same.\"",
        "Ronan shrugged. \"I haven't had time to redecorate.\"",
        "Evelyn noticed the loaf of bread wrapped in brown paper. She picked it up gently. \"Yesterday's bread?\"",
        "Ronan remained silent. For a brief moment, something like sadness crossed her face. But she carefully placed the loaf back on the table without another comment.",
        "Instead, she lifted a small paper bag from behind her back. \"I brought coffee,\" she announced. \"And before you say anything—no, you are not refusing it.\"",
        "Ronan laughed quietly. \"You always win these arguments.\"",
        "\"Of course I do.\"",
        "They sat across from each other, and for a few peaceful minutes neither of them mentioned the murder. The silence felt familiar. Comfortable. Like two people who had known each other long before London learned their names.",
        "Finally, Evelyn opened her notebook. \"The whole city is talking about London Bridge,\" she said softly.",
        "Ronan nodded. \"I noticed.\"",
        "\"The London Times hasn't covered a story this big in years.\" She leaned forward slightly. \"And Ronan... the Royal Palace is hiding something.\"",
        "Ronan looked at her carefully. \"You sound very certain.\"",
        "Evelyn smiled faintly. \"I have sources.\"",
        "Outside, distant church bells echoed through the streets of London as the city continued whispering about the murder that had changed everything.",
        "For a brief moment... Neither of them spoke. The room remained silent until loud voices echoed from outside.",
        "\"RONAN! Come out already! We're going to be late!\"",
        "Evelyn smiled. \"They're here.\"",
        "Ronan shook his head with a small laugh. \"My daily headache.\"",
        "He opened the door. Standing outside were two young men wearing dusty factory uniforms. One was tall and broad-shouldered. The other looked younger, carrying his coat over one shoulder. Samuel Brooks. Oliver Hayes.",
        "Both had been Ronan's closest friends since childhood. Samuel grinned the moment he saw him. \"There he is. The world's poorest detective.\"",
        "Oliver laughed. \"And somehow still richer than us in respect.\"",
        "Ronan folded his arms. \"You two only come here when you want something.\"",
        "Samuel pointed toward the street. \"We're done with work early today. So... You're coming with us.\"",
        "\"Where?\"",
        "\"The tavern.\"",
        "Ronan sighed. \"I don't have money.\"",
        "Samuel rolled his eyes. \"You never do.\"",
        "Oliver laughed. \"That's why we're paying.\"",
        "Before Ronan could refuse... Samuel grabbed his shoulder. \"No excuses. You've been locked inside this house since yesterday. You need fresh air.\"",
        "Evelyn stood up, closing her notebook. \"I'll come too.\"",
        "Samuel smiled. \"Perfect. Now he'll have no excuse.\"",
        "A few minutes later... The four of them walked through London's crowded streets. Workers were returning from the factories. The smell of coal filled the air. Horse-drawn carriages rattled over the wet stone roads. Despite everything that had happened... Life in London refused to stop.",
        "The tavern was warm. Dim lanterns hung from wooden beams. Workers laughed loudly over cheap whisky. A violinist played quietly in one corner.",
        "Samuel immediately ordered drinks. Three glasses of whisky. One cup of black coffee.",
        "Oliver frowned. \"You still won't drink?\"",
        "Ronan picked up the coffee. \"I like remembering what happened the next morning.\"",
        "The table erupted with laughter.",
        "For a while... They forgot about the murder. They talked about work. Old memories. Childhood. Life.",
        "Then Evelyn suddenly placed today's newspaper on the table. The headline immediately silenced everyone: LONDON BRIDGE MURDER SHOCKS THE KINGDOM.",
        "Samuel looked toward her. \"So... What are people saying now?\"",
        "Evelyn crossed her arms. \"The city thinks this is just another murder.\" She paused. \"The Royal Palace doesn't.\"",
        "Everyone became quiet.",
        "\"I've been speaking with a few sources this morning. They told me something interesting. The Palace spent the entire night arguing. They're trying to decide who should handle the investigation.\"",
        "Oliver leaned forward. \"So they're finally doing something.\"",
        "\"They have to. The victim wasn't an ordinary noble. He represented the kingdom in foreign affairs. If other nations hear about this... The King's reputation will suffer.\"",
        "Samuel lowered his voice. \"So who are they assigning?\"",
        "Evelyn glanced around before speaking. \"They've already selected one of the kingdom's most respected forensic examiners, Dr. Theodore Graves. And an honest police inspector, Inspector Elias Ward.\"",
        "Ronan listened quietly. \"What makes them different?\"",
        "\"They can't be bought.\"",
        "Samuel let out a low whistle. \"So the Palace actually wants the truth?\"",
        "Evelyn slowly shook her head. \"No. They want control. If the public discovers what Lord Beaumont was truly involved in... The kingdom could lose faith in the nobles. They're trying to stop panic before it begins.\"",
        "Oliver frowned. \"So what now?\"",
        "Evelyn looked directly at Ronan. \"My source also said something else. The ministers are looking for someone... who has no ties to noble families... someone the public already trusts... someone independent.\"",
        "Ronan remained silent. For some reason... That sentence stayed in his mind.",
        "Outside... Thunder rolled across London's sky. Rain began striking the tavern windows. Ronan stared quietly into his untouched coffee.",
        "Then... Something flashed through his memory. His eyes widened. The bridge. The body. The blood. And... Something else. Something he had ignored.",
        "He slowly stood up. Samuel frowned. \"Ronan?\"",
        "He didn't answer. \"I missed something.\"",
        "The table fell silent. \"What do you mean?\"",
        "Ronan looked toward the rain outside. \"There was something near the crime scene. Not beside the body... Near the edge of the bridge.\"",
        "Without another word... He grabbed his coat and rushed toward the tavern door. Evelyn immediately stood. \"Ronan!\"",
        "The tavern door slammed shut behind Ronan. Cold rain immediately soaked his coat. He ignored it. His heart pounded faster with every step.",
        "The streets blurred around him as he ran through the darkness. People shouted. Carriages rushed past. The city continued moving. But Ronan heard none of it. Only one thought echoed inside his mind: The bridge.",
        "He remembered standing beside Lord Beaumont's body. He remembered the blood. The Royal Guards. The growing crowd. And then... Something near the edge of the bridge. Something he had dismissed in the chaos. He should have checked. He should have looked closer.",
        "Behind him, Evelyn called out his name, but the rain swallowed her voice.",
        "Within minutes... London Bridge emerged through the thick blanket of fog. The crime scene had already been abandoned. The Guards were gone. Only silence remained. Rainwater slowly washed away the last traces of blood.",
        "Ronan walked toward the exact place where Lord Beaumont's body had been discovered. His breathing slowed. Every detail returned to him.",
        "Ten feet away... Near the old stone railing. There. He knelt. His fingers searched carefully between the cracks in the weathered stones. Nothing. He searched again. Still nothing.",
        "Then... His fingertips brushed against something thin. Paper. Carefully... He pulled it free.",
        "A single playing card. The Fool.",
        "His heartbeat stopped. It looked identical to the first one. But this one... Had something written on the back. Ronan slowly turned the card over. Only one sentence:",
        "\"You're looking in the wrong direction.\"",
        "For several long seconds... He couldn't move. The cold wind swept across London Bridge. His eyes instinctively searched the rooftops. The towers. The empty streets. The darkness hidden behind the fog. Nothing. No footsteps. No movement. Only silence.",
        "Yet... For the first time in his life... Ronan felt certain of one thing. The killer had never truly left. He had simply been watching. Watching the police. Watching the Royal Guards. Watching... Everyone.",
        "A distant church bell echoed across London. One... Two... Three... Midnight.",
        "Ronan carefully slipped the card inside his coat. His expression had completely changed. This was no longer just another murder investigation. Someone had planned every step. Someone had expected the authorities to overlook the second card. Someone wanted the investigation to begin exactly this way.",
        "Far beyond the bridge... Hidden somewhere within London's endless fog... A lone figure stood motionless. For just a brief moment... A faint smile appeared beneath the shadow of a wide-brimmed hat. Then the figure quietly disappeared into the darkness.",
        "Ronan remained standing on the bridge, the rain falling around him. He looked once more at the empty road stretching into the night.",
        "Somewhere in this city... A murderer was waiting. And for the first time... Ronan realized he wasn't simply investigating a crime. He had stepped into someone else's plan."
      ]
    }
  ]
};